# Generated by Django 5.0.9 on 2024-12-07 14:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_assessmenttype_enrollment_come_back_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursematerial",
            name="expect_duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
