# Generated by Django 5.1.3 on 2024-12-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_alter_member_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='role',
            new_name='role_member',
        ),
    ]
