# Generated by Django 5.1.3 on 2024-12-06 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_assessmenttype_enrollment_come_back_and_more'),
        ('feedback', '0004_rename_comments_coursefeedback_course_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorfeedback',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='course.course'),
        ),
    ]
