# Generated by Django 5.1.1 on 2024-11-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_studentanswer_selected_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
