# Generated by Django 5.1.1 on 2024-10-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_commentreaction_threadreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionthread',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='loves_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
