# Generated by Django 5.1.2 on 2024-12-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0008_threadcomments_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadcomments',
            name='parent',
        ),
    ]
