# Generated by Django 5.1.1 on 2024-12-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_alter_role_options_remove_role_modules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
