# Generated by Django 5.0.9 on 2024-11-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinsights',
            name='insight_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
