# Generated by Django 5.1.3 on 2024-12-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_modified',
        ),
    ]
