# Generated by Django 5.1.1 on 2024-10-03 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png'])]),
        ),
    ]
