# Generated by Django 5.1.1 on 2024-10-10 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_usernotificationstatus_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationstatus',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='notifications.notification'),
        ),
    ]
