# Generated by Django 5.1.1 on 2024-10-10 02:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_alter_usernotificationstatus_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserNotificationStatus',
        ),
    ]
